version: '3'

services:

  nm64:
    build:
      context: .
      dockerfile: Dockerfiles/Debian64.Dockerfile
    volumes:
    - .:/code
    tty: true
    container_name: nm64_pde-bakk

  nm32:
    build:
      context: .
      dockerfile: Dockerfiles/Debian32.Dockerfile
    volumes:
      - .:/code
    tty: true
    container_name: nm32_pde-bakk
